// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:42722e46-da6c-4ac5-87b7-ffe5d9e30c26",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ujIqGnd5j",
    "aws_user_pools_web_client_id": "e926nehfc4sff9hfvri9qjd21"
};


export default awsmobile;
