// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ea34d22e-888d-4fc5-9374-86b3e10bbbc0",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_uumfrvMmv",
    "aws_user_pools_web_client_id": "11lhp4rl68cpbgodkkbaqrba38",
    "aws_content_delivery_bucket": "client-20190324005600-hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d1ixyendek9ha.cloudfront.net",
    "aws_cloud_logic_custom": [
        {
            "name": "zentalityapi",
            "endpoint": "https://ly7oo0a325.execute-api.us-east-1.amazonaws.com/Prod",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
